---
abstract: 'Interface to the Copenhagen Tube Map.'
author:
  - 'Søren Lund <soren@lund.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.143240'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Map-Tube-Copenhagen
no_index:
  directory:
    - t
    - inc
requires:
  File::Share: '0.25'
  Map::Tube: '3.40'
  Moo: '2.000000'
  namespace::autoclean: '0.28'
  perl: '5.006'
version: '0.01'
